### ISSUE TITLE
synchronize translation files

### ISSUE THREAD

**Issue by dbu** [Incenteev/translation-checker-bundle#1]
we did a synchronize translation command in one of our projects. it is atm quite specific to our situation, but could be generalized and integrated into this bundle: https://gist.github.com/dbu/5883029

it looks for message catalogues and makes sure they exist in other languages and adds all missing keys to make it really easy to add missing translations.

**Comment by stof** [comment]
I'm closing this, as nobody was interested into implementing this in 5 years (and I'm not).
